server:
  port: 3001

spring:
  # 데이터 베이스 연결 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PROJECT_BE
    password: _aA123456

  # JPA 설정
  jpa:
    properties:
      hibernate:
        # 실행되는 쿼리 콘솔 출력
        show_sql: true
        # 콘솔 창에 출력되는 쿼리를 가독성 좋게 포매팅
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddlAuto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# JSON WebToken 설정
jwt:
  header: Authorization
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM # base64 인코딩
  accessTokenValidityInSeconds: 3600 # 60 min